# Generated by Django 3.0.6 on 2020-06-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200604_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_dat',
            new_name='pub_date',
        ),
    ]
